# Generated by Django 3.0.5 on 2020-05-08 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_auto_20200507_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='all_course',
            name='permision',
            field=models.IntegerField(default=0),
        ),
    ]
