# Generated by Django 2.2.12 on 2020-05-14 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='ratting',
        ),
        migrations.AddField(
            model_name='all_course',
            name='intro_text',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='review',
            name='permission',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='all_lesson',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
