# Generated by Django 2.2.12 on 2020-05-26 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_auto_20200514_1740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='ratting',
            field=models.IntegerField(default=5),
        ),
    ]
