# Generated by Django 2.2.16 on 2020-09-29 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_auto_20200526_1152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_lesson',
            name='link',
            field=models.URLField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='all_lesson',
            name='title',
            field=models.CharField(max_length=1000),
        ),
    ]
