# Generated by Django 2.2.16 on 2020-10-12 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_auto_20200929_1006'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_form',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='')),
                ('email', models.CharField(max_length=100, verbose_name='')),
                ('message', models.CharField(max_length=1000, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='ki_ki_sikhben',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_num', models.IntegerField(default=0)),
                ('details', models.CharField(max_length=2000, verbose_name='')),
            ],
        ),
        migrations.RemoveField(
            model_name='all_course',
            name='number',
        ),
        migrations.RemoveField(
            model_name='all_lesson',
            name='course_Num',
        ),
        migrations.RemoveField(
            model_name='all_lesson',
            name='lesson_Num',
        ),
        migrations.AddField(
            model_name='all_course',
            name='course_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='all_lesson',
            name='course_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='all_lesson',
            name='lesson_num',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='all_course',
            name='intro_text',
            field=models.CharField(default='', max_length=5000),
        ),
        migrations.AlterField(
            model_name='all_course',
            name='title',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='all_lesson',
            name='link',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='all_lesson',
            name='title',
            field=models.CharField(max_length=5000),
        ),
        migrations.CreateModel(
            name='course_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_num', models.IntegerField(default=0)),
                ('keno_korben', models.CharField(max_length=1000, verbose_name='')),
                ('keno_korben_details', models.CharField(max_length=10000, verbose_name='')),
                ('ki_ki_sikhte_parben', models.CharField(max_length=1000, verbose_name='')),
                ('ki_ki_sikhte_parben_details', models.ManyToManyField(to='course.ki_ki_sikhben', verbose_name='list of sites')),
            ],
        ),
    ]
