# Generated by Django 3.0.5 on 2020-05-08 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_all_course_permision'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='all_course',
            name='permision',
        ),
        migrations.AddField(
            model_name='all_lesson',
            name='permision',
            field=models.IntegerField(default=0),
        ),
    ]
