# Generated by Django 3.0.5 on 2020-05-08 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20200508_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bkash',
            name='date_subscribed',
        ),
        migrations.AlterField(
            model_name='bkash',
            name='transaction_id',
            field=models.CharField(max_length=40),
        ),
    ]
