# Generated by Django 3.0.5 on 2020-05-08 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200508_1652'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkash',
            name='course_id',
            field=models.IntegerField(default=1),
        ),
    ]
