# Generated by Django 3.0.5 on 2020-05-08 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_bkash_course_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bkash',
            name='permision',
            field=models.IntegerField(default=0),
        ),
    ]
