# Generated by Django 3.0.5 on 2020-05-08 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_bkash_permision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bkash',
            name='permision',
            field=models.IntegerField(default=5),
        ),
    ]
